# Generated by Django 4.0 on 2022-01-04 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0003_remove_game_game_name_remove_game_gametype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
    ]
